In [1]:
import numpy as np

In [3]:
# ALl zeros matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [6]:
# All ones matrix
b = np.ones((4,4,2), dtype='int32')

In [5]:
# Any other number
np.full((4,4), 21)

array([[21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21]])

In [7]:
# Full like: eg like b
np.full_like(b, 4)

array([[[4, 4],
        [4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4],
        [4, 4]]], dtype=int32)

In [8]:
# Random Decimal Number
np.random.rand(4,2)

array([[0.18561473, 0.54259303],
       [0.10653416, 0.60936741],
       [0.08644469, 0.55615867],
       [0.24796685, 0.30512056]])

In [9]:
# Random Integers Value
np.random.randint(-4,8, size=(3,3))

array([[ 5, -2,  4],
       [ 6,  6,  2],
       [ 6,  6,  3]], dtype=int32)

In [12]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
output = np.ones((5,5))
output[1:-1,1:-1] = 0
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
