In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a[1,5]

np.int64(13)

In [11]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,3]

array([ 4, 11])

In [13]:
b = np.array([[
    [1,2],
    [3,4]],
    [[5,6],
     [7,8]]
])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
