In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [4]:
a + 2 # can do same with others

array([5, 6, 7, 8])

In [5]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

## Linear Algebra

In [7]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [8]:
# Find the Determinants
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Statistics

In [13]:
stats = np.array([[1,2,3],[4,5,6], [0,0,0]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [14]:
np.min(stats, axis=0)

array([0, 0, 0])

In [17]:
np.sum(stats,axis=1)

array([ 6, 15,  0])