## Load Data From File (Without Pandas)

In [1]:
import numpy as np

In [4]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31 32 33]]


#### Advanced Indexing

In [6]:
filedata[filedata  > 20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], dtype=int32)