In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

mod = arr.reshape((2,2,2))
print(mod)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# Vertically STacking Matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v1,v2,v1])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [5]:
# Horizontal Stack

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])